<a href="https://colab.research.google.com/github/DaryaJavadi/data_science/blob/main/projects/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Path to dataset files: /root/.cache/kagglehub/datasets/yasserh/titanic-dataset/versions/1


In [ ]:
df = pd.read_csv(path + "/Titanic-Dataset.csv")
df = df[df['Fare'] != 0]
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[876 rows x 12 columns]

In [ ]:
df.drop(columns = ['PassengerId', 'Name'], axis=1, inplace = True)


In [ ]:
X = df.drop('Survived', axis = 1)
y = df['Survived'].copy()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 876 entries, 0 to 890
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  876 non-null    int64  
 1   Pclass    876 non-null    int64  
 2   Sex       876 non-null    object 
 3   Age       707 non-null    float64
 4   SibSp     876 non-null    int64  
 5   Parch     876 non-null    int64  
 6   Ticket    876 non-null    object 
 7   Fare      876 non-null    float64
 8   Cabin     201 non-null    object 
 9   Embarked  874 non-null    object 
dtypes: float64(2), int64(4), object(4)
memory usage: 75.3+ KB


In [ ]:
X_num=X_train.select_dtypes(include=[np.number])
X_cat=X_train.select_dtypes(include='object')
X_num, X_cat

(     Pclass   Age  SibSp  Parch     Fare
 403       3  28.0      1      0  15.8500
 553       3  22.0      0      0   7.2250
 530       2   2.0      1      1  26.0000
 780       3  13.0      0      0   7.2292
 236       2  44.0      1      0  26.0000
 ..      ...   ...    ...    ...      ...
 106       3  21.0      0      0   7.6500
 273       1  37.0      0      1  29.7000
 875       3  15.0      0      0   7.2250
 441       3  20.0      0      0   9.5000
 102       1  21.0      0      1  77.2875
 
 [700 rows x 5 columns],
         Sex            Ticket Cabin Embarked
 403    male  STON/O2. 3101279   NaN        S
 553    male              2620   NaN        C
 530  female             26360   NaN        S
 780  female              2687   NaN        C
 236    male             26707   NaN        S
 ..      ...               ...   ...      ...
 106  female            343120   NaN        S
 273    male          PC 17596  C118        C
 875  female              2667   NaN        C
 441    m

In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy = 'median')
imputer.fit(X_num)

SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_

array([ 3.     , 28.5    ,  0.     ,  0.     , 14.45625])

In [ ]:
pd.DataFrame(imputer.transform(X_num), columns = imputer.feature_names_in_)

Pclass   Age  SibSp  Parch     Fare
0       3.0  28.0    1.0    0.0  15.8500
1       3.0  22.0    0.0    0.0   7.2250
2       2.0   2.0    1.0    1.0  26.0000
3       3.0  13.0    0.0    0.0   7.2292
4       2.0  44.0    1.0    0.0  26.0000
..      ...   ...    ...    ...      ...
695     3.0  21.0    0.0    0.0   7.6500
696     1.0  37.0    0.0    1.0  29.7000
697     3.0  15.0    0.0    0.0   7.2250
698     3.0  20.0    0.0    0.0   9.5000
699     1.0  21.0    0.0    1.0  77.2875

[700 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoder.fit(X_cat)

OneHotEncoder()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder()
encoder.fit_transform(X_cat)

array([[  1., 549.,  nan,   2.],
       [  1., 132.,  nan,   0.],
       [  0., 140.,  nan,   2.],
       ...,
       [  0., 154.,  nan,   0.],
       [  1., 244.,  nan,   2.],
       [  1., 338.,  76.,   2.]])

In [ ]:
encoder.categories_

[array(['female', 'male'], dtype=object),
 array(['110152', '110413', '110813', '111240', '111361', '111369',
        '111426', '111427', '111428', '112053', '112277', '112379',
        '113028', '113051', '113055', '113059', '113503', '113505',
        '113510', '113514', '113572', '113760', '113767', '113773',
        '113776', '113781', '113783', '113786', '113787', '113789',
        '113792', '113794', '113796', '113798', '113800', '113803',
        '113804', '113806', '113807', '11668', '11751', '11753', '11755',
        '11767', '11769', '11771', '11813', '11967', '12233', '12460',
        '12749', '13213', '13214', '13502', '13507', '13509', '13567',
        '13568', '14311', '14312', '14313', '1601', '16966', '16988',
        '17421', '17463', '17465', '17466', '17474', '19877', '19928',
        '19943', '19947', '19950', '19952', '19988', '19996', '2003',
        '21440', '218629', '219533', '220367', '220845', '2223', '223596',
        '226875', '228414', '229236', '230080', 

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()
encoder.fit_transform(X_cat).toarray()

array([[0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range = (-1, 1))
pd.DataFrame(scaler.fit_transform(X_num), columns = scaler.feature_names_in_)

Pclass       Age  SibSp     Parch      Fare
0       1.0 -0.306861  -0.75 -1.000000 -0.953425
1       1.0 -0.457653  -1.00 -1.000000 -0.987360
2       0.0 -0.960292  -0.75 -0.666667 -0.913489
3       1.0 -0.683840  -1.00 -1.000000 -0.987344
4       0.0  0.095250  -0.75 -1.000000 -0.913489
..      ...       ...    ...       ...       ...
695     1.0 -0.482785  -1.00 -1.000000 -0.985688
696    -1.0 -0.080674  -1.00 -0.666667 -0.898931
697     1.0 -0.633576  -1.00 -1.000000 -0.987360
698     1.0 -0.507917  -1.00 -1.000000 -0.978409
699    -1.0 -0.482785  -1.00 -0.666667 -0.711695

[700 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
pd.DataFrame(scaler.fit_transform(X_num), columns = scaler.feature_names_in_)

Pclass       Age     SibSp     Parch      Fare
0    0.790212 -0.110012  0.384959 -0.485170 -0.314162
1    0.790212 -0.523826 -0.489948 -0.485170 -0.483172
2   -0.428177 -1.903206  0.384959  0.749809 -0.115269
3    0.790212 -1.144547 -0.489948 -0.485170 -0.483090
4   -0.428177  0.993491  0.384959 -0.485170 -0.115269
..        ...       ...       ...       ...       ...
695  0.790212 -0.592795 -0.489948 -0.485170 -0.474844
696 -1.646565  0.510709 -0.489948  0.749809 -0.042767
697  0.790212 -1.006609 -0.489948 -0.485170 -0.483172
698  0.790212 -0.661764 -0.489948 -0.485170 -0.438593
699 -1.646565 -0.592795 -0.489948  0.749809  0.889728

[700 rows x 5 columns]

In [ ]:
from sklearn.preprocessing import FunctionTransformer

log_transformer = FunctionTransformer(np.log, inverse_func = np.exp)
log_pop = log_transformer.transform(X_train[['Fare']])
pd.DataFrame(log_pop, columns = ['Fare']).min()

Fare    1.389414
dtype: float64

In [ ]:
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.compose import ColumnTransformer

X_num_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'median')),
    ('scale', StandardScaler())
])


X_cat_pipeline = Pipeline([
    ('impute', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder(sparse_output=False, handle_unknown = 'ignore'))
])


X_num_cols = X_train.select_dtypes(include = np.number).columns
X_cat_cols = X_train.select_dtypes(include = 'object').columns


transformer = ColumnTransformer([
    ('num', X_num_pipeline, X_num_cols),
    ('cat', X_cat_pipeline, X_cat_cols)
])

X_prepared = pd.DataFrame(transformer.fit_transform(X_train),
                          columns = transformer.get_feature_names_out())
X_prepared

num__Pclass  num__Age  num__SibSp  num__Parch  num__Fare  \
0       0.790212 -0.106233    0.384959   -0.485170  -0.314162   
1       0.790212 -0.565778   -0.489948   -0.485170  -0.483172   
2      -0.428177 -2.097592    0.384959    0.749809  -0.115269   
3       0.790212 -1.255094   -0.489948   -0.485170  -0.483090   
4      -0.428177  1.119218    0.384959   -0.485170  -0.115269   
..           ...       ...         ...         ...        ...   
695     0.790212 -0.642368   -0.489948   -0.485170  -0.474844   
696    -1.646565  0.583083   -0.489948    0.749809  -0.042767   
697     0.790212 -1.101913   -0.489948   -0.485170  -0.483172   
698     0.790212 -0.718959   -0.489948   -0.485170  -0.438593   
699    -1.646565 -0.642368   -0.489948    0.749809   0.889728   

     cat__Sex_female  cat__Sex_male  cat__Ticket_110152  cat__Ticket_110413  \
0                0.0            1.0                 0.0                 0.0   
1                0.0            1.0                 0.0                 0.0   
2                1.0            0.0                 0.0                 0.0   
3                1.0            0.0                 0.0                 0.0   
4                0.0            1.0                 0.0                 0.0   
..               ...            ...                 ...                 ...   
695              1.0            0.0                 0.0                 0.0   
696              0.0            1.0                 0.0                 0.0   
697              1.0            0.0                 0.0                 0.0   
698              0.0            1.0                 0.0                 0.0   
699              0.0            1.0                 0.0                 0.0   

     cat__Ticket_110813  ...  cat__Cabin_F E69  cat__Cabin_F G73  \
0                   0.0  ...               0.0               0.0   
1                   0.0  ...               0.0               0.0   
2                   0.0  ...               0.0               0.0   
3                   0.0  ...               0.0               0.0   
4                   0.0  ...               0.0               0.0   
..                  ...  ...               ...               ...   
695                 0.0  ...               0.0               0.0   
696                 0.0  ...               0.0               0.0   
697                 0.0  ...               0.0               0.0   
698                 0.0  ...               0.0               0.0   
699                 0.0  ...               0.0               0.0   

     cat__Cabin_F2  cat__Cabin_F33  cat__Cabin_F38  cat__Cabin_F4  \
0              0.0             0.0             0.0            0.0   
1              0.0             0.0             0.0            0.0   
2              0.0             0.0             0.0            0.0   
3              0.0             0.0             0.0            0.0   
4              0.0             0.0             0.0            0.0   
..             ...             ...             ...            ...   
695            0.0             0.0             0.0            0.0   
696            0.0             0.0             0.0            0.0   
697            0.0             0.0             0.0            0.0   
698            0.0             0.0             0.0            0.0   
699            0.0             0.0             0.0            0.0   

     cat__Cabin_G6  cat__Embarked_C  cat__Embarked_Q  cat__Embarked_S  
0              0.0              0.0              0.0              1.0  
1              0.0              1.0              0.0              0.0  
2              0.0              0.0              0.0              1.0  
3              0.0              1.0              0.0              0.0  
4              0.0              0.0              0.0              1.0  
..             ...              ...              ...              ...  
695            0.0              0.0              0.0              1.0  
696            0.0              1.0              0.0 

In [ ]:
from sklearn.ensemble import RandomForestClassifier

rnd_clf = RandomForestClassifier()

rnd_clf.fit(X_prepared, y_train)

RandomForestClassifier()

In [ ]:
X_prepared_test = pd.DataFrame(transformer.transform(X_test),
                          columns = transformer.get_feature_names_out())

In [ ]:
rnd_clf.score(X_prepared_test, y_test)

0.8409090909090909