<a href="https://colab.research.google.com/github/DaryaJavadi/data_science/blob/main/basics/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a1 = np.array([1,2,3])
a1.ndim, a1.shape, a1.dtype, type(a1), a1.size

(1, (3,), dtype('int64'), numpy.ndarray, 3)

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2 = np.array([[1,2,3],
              [4,5,6]])
a2.ndim, a2.shape, a2.dtype, type(a2), a2.size

(2, (2, 3), dtype('int64'), numpy.ndarray, 6)

In [ ]:
a3 = np.array([[[1, 2, 3],
              [4, 5, 6]],
              [[5, 6, 7],
               [2, 3, 4]]])
a3.ndim, a3.shape, a3.dtype, type(a3), a3.size

(3, (2, 2, 3), dtype('int64'), numpy.ndarray, 12)

In [ ]:
random_arr = np.random.randint(0, 10, size=(3, 2, 5, 3))
random_arr.ndim, random_arr.shape, random_arr.dtype, type(random_arr), random_arr.size

(4, (3, 2, 5, 3), dtype('int64'), numpy.ndarray, 90)

In [ ]:
# random_arr = np.random.randint(0, 255, size=(300, 300, 3))
# random_arr

In [ ]:
np.random.rand(100)

array([0.94876712, 0.13670375, 0.25419297, 0.6545703 , 0.42720462,
       0.98487057, 0.76264224, 0.43088874, 0.51703383, 0.66613589,
       0.97057978, 0.93310159, 0.20930413, 0.11085202, 0.3659938 ,
       0.42932348, 0.08230473, 0.86234905, 0.23322963, 0.45187005,
       0.3778758 , 0.08619999, 0.95844873, 0.1299816 , 0.69079127,
       0.69943686, 0.54049361, 0.89424335, 0.33790979, 0.85280292,
       0.70350227, 0.05028305, 0.82841995, 0.39896814, 0.48901025,
       0.07368358, 0.85929548, 0.62001997, 0.89509557, 0.32058456,
       0.25226913, 0.89990094, 0.22943061, 0.16511046, 0.49378873,
       0.6611792 , 0.7838228 , 0.78154968, 0.17417081, 0.42365935,
       0.38704539, 0.82265039, 0.19456341, 0.13986868, 0.1052567 ,
       0.5403302 , 0.8465687 , 0.5557568 , 0.6135    , 0.01815422,
       0.78255374, 0.90527265, 0.14251548, 0.92418402, 0.8105198 ,
       0.79482267, 0.75632723, 0.36491335, 0.93786111, 0.00549699,
       0.74571481, 0.91386515, 0.13184718, 0.61096535, 0.60814

In [ ]:
np.random.randn(100)

array([ 1.55378112, -0.79485011,  0.80774932,  1.1882387 , -2.31870065,
       -1.50533745, -2.09515586,  1.09965935, -0.22627758, -2.05910093,
        0.46025114, -0.98118245,  1.02935903,  1.2102024 ,  0.56546828,
        1.51705113,  1.34718817, -0.48987043, -0.26454722, -1.18923535,
       -0.67797054,  0.61936055, -0.44891475,  0.72034377, -1.05497271,
        1.02516454, -0.5436104 ,  0.94018691, -1.2590642 , -1.1988523 ,
       -0.81056157,  1.09661435, -0.44200298, -2.07249882,  1.04214798,
        1.32805325, -1.31119079, -0.72728136,  0.1856199 , -0.61998536,
       -1.86164055, -0.04488851,  0.62484867, -0.11554908, -1.28544867,
       -0.69022742,  1.32782985,  0.04485882, -0.02455571, -1.89839561,
       -0.31679816,  0.57123348,  0.17045138, -0.98234622, -0.04604119,
       -1.65174839,  0.86017201, -0.07242638, -0.93286166, -1.2475298 ,
        0.35031499, -0.50613799, -0.46736941, -1.20086516,  0.04513331,
        1.19963095, -0.49123587,  0.66394961,  0.75495159, -0.99

In [ ]:
np.random.seed(1)
random_arr = np.random.randint(1, 10, size=(5, 5))
random_arr[2]

array([6, 3, 5, 3, 5])

In [ ]:
np.random.seed(1)
random_arr = np.random.randint(1, 10, size=(2, 5, 5))
random_arr[:, 2:, 2]

array([[5, 2, 7],
       [9, 3, 8]])

In [ ]:
import time

start = time.time()
arr = np.arange(1000000)
arr**20
end = time.time()
end - start

0.0214078426361084

In [ ]:
a1 * 2

array([2, 4, 6])

In [ ]:
a1 + a1

array([2, 4, 6])

In [ ]:
a2 + a1

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
a1.shape, a2.shape

((3,), (2, 3))

In [ ]:
a2.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
a2.shape, a2.T.shape

((2, 3), (3, 2))

In [ ]:
a2 @ a2.T

array([[14, 32],
       [32, 77]])

In [ ]:
np.dot(a2, a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np.matmul(a2, a2.T)

array([[14, 32],
       [32, 77]])

In [ ]:
np.zeros(shape = (5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.std(a3)

1.7795130420052185

In [ ]:
np.var(a3)

3.1666666666666665

In [ ]:
np.std(a3)

1.7795130420052185

In [ ]:
np.sum(a3)

48

In [ ]:
a3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [2, 3, 4]]])